export const CREATE_BOOK_REQUEST="CREATE_BOOK_REQUEST";
export const CREATE_BOOK_SUCCESS="CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAIL="CREATE_BOOK_FAIL";
export const FETCH_BOOKS="FETCH_BOOKS";

