export const CREATE_BOOK_REQUEST="CREATE_BOOK_REQUEST";
export const CREATE_BOOK_SUCCESS="CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAIL="CREATE_BOOK_FAIL";

export const FETCH_BOOKS="FETCH_BOOKS";

export const ADDTOSHELF_BOOK_REQUEST="ADDTOSHELF_BOOK_REQUEST";
export const ADDTOSHELF_BOOK_SUCCESS="ADDTOSHELF_BOOK_SUCCESS";
export const ADDTOSHELF_BOOK_FAIL="ADDTOSHELF_BOOK_FAIL";

export const FETCH_BOOKSHELF="FETCH_BOOKSHELF";


