export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS="LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAIL="LOGIN_REQUEST_FAIL";

export const USER_LOGOUT_SUCCESS="USER_LOGOUT_SUCCESS";